spring:
  application:
    name: pi
  datasource:
    url: jdbc:postgresql://localhost:5432/clinigestdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect